In [1]:
import numpy as np

In [ ]:
# gerando numeros aleatorios l
rng = np.random.default_rng()
print('Numeros aleatorios: ')
print(rng.random(4) * 10)

Numeros aleatorios: 
[2.26803623 1.23387869 9.32762919 7.48605839]


In [4]:
# exercicio 
# gere 500.000 numeros aleatorios 
num_aleatorio = np.random.default_rng()
print(num_aleatorio.random(2) * 500)
# mostre o maior e menor do array 
array_brincando = np.array(rng.random(500_000) * 4_000)
menor = np.min(array_brincando)
print('Menor valor: ',menor)
maior = np.max(array_brincando)
print('Maior valor: ',maior)
# mostre a media dos soma_valores
media = np.mean(array_brincando)
print('Média: ',media)

[ 11.44192774 487.36008884]
Menor valor:  0.00033015139999648113
Maior valor:  3999.985483884979
Média:  1997.3065795208977


In [ ]:
# GERAR NÚMEROS ALEATORIO INTEIROS
array_inteiro = np.array(np.random.randint(1, 11, 5))
print(array_inteiro)
# Geração de números aleatorios
# os parametros são: valor mais baixo, valor mais alto e quantidade
# guarde no arry



[ 7  3 10  7  1]


In [11]:
# ---------------------------------------- 
# gerando uma matriz BI-dimensional (D2) 
print('------- gerando Matrizes  -------')
matriz_inteiro = np.array(np.random.randint(1, 11, size=(2,2)))
print(matriz_inteiro)

------- gerando Matrizes  -------
[[ 7 10]
 [10  8]]


In [12]:
# verificar se um array tem valores 
print(np.isnan(array_inteiro))

[False False False False False]


In [21]:
# organizar os avlores em ordem crescente
print(array_inteiro)
print("Em ordem crescente: ",np.sort(array_inteiro))

[ 7  3 10  7  1]
Em ordem crescente:  [ 1  3  7  7 10]


In [22]:
# organizar os avlores em ordem decrescente
print(array_inteiro)
print("Em ordem decrescente: ",np.sort(array_inteiro)[::-1])

[ 7  3 10  7  1]
Em ordem decrescente:  [10  7  7  3  1]


In [ ]:
# EXER 
# crie um array de 1 diemensão,. preencha com 900 mil registro
# variando de 20 a 15000 
valores_array = np.array(np.random.randint(1, 1000, 900000))
print(valores_array) 

[ 15 553 685]


In [ ]:
# mostre a média de desses volores
media_array = np.sum(valores_array)
print(media_array)

449849944


In [42]:
# mostre o primeiro e ultimo valor
print('Primeiro valor:')
print(valores_array[0])
print('Ultimo valor: ')
print(valores_array[-1])

Primeiro valor:
15
Ultimo valor: 
685


In [33]:
# mostre o maior e menor valor
maior_valor = np.max(valores_array)
print('Maior valor: ',maior_valor)
menor_valor = np.min(valores_array)
print('Maior valor: ',menor_valor)

Maior valor:  999
Maior valor:  1


In [36]:
# mostre o valor em ordem decrescente
print('Array inicial: ')
print(valores_array)

print('Array em ordem dexrescente: ')
print(np.sort(valores_array)[::-1])

Array inicial: 
[556 555 433 ... 668 495 330]
Array em ordem dexrescente: 
[999 999 999 ...   1   1   1]


In [43]:
# conta os valores unicos e suas repetições 
array_exer = np.array(np.random.randint(20, 15_000, 900_000))

valores_unicos, contagem = np.unique(array_exer, return_counts=True)
for valor , cont in zip(valores_unicos, contagem):
    print(f'Valor {valor} - contagem {cont}')

Valor 20 - contagem 68
Valor 21 - contagem 63
Valor 22 - contagem 59
Valor 23 - contagem 64
Valor 24 - contagem 60
Valor 25 - contagem 54
Valor 26 - contagem 63
Valor 27 - contagem 69
Valor 28 - contagem 50
Valor 29 - contagem 54
Valor 30 - contagem 68
Valor 31 - contagem 64
Valor 32 - contagem 53
Valor 33 - contagem 65
Valor 34 - contagem 70
Valor 35 - contagem 56
Valor 36 - contagem 62
Valor 37 - contagem 67
Valor 38 - contagem 65
Valor 39 - contagem 51
Valor 40 - contagem 58
Valor 41 - contagem 62
Valor 42 - contagem 55
Valor 43 - contagem 65
Valor 44 - contagem 67
Valor 45 - contagem 69
Valor 46 - contagem 60
Valor 47 - contagem 53
Valor 48 - contagem 57
Valor 49 - contagem 55
Valor 50 - contagem 51
Valor 51 - contagem 60
Valor 52 - contagem 39
Valor 53 - contagem 61
Valor 54 - contagem 65
Valor 55 - contagem 58
Valor 56 - contagem 58
Valor 57 - contagem 76
Valor 58 - contagem 58
Valor 59 - contagem 67
Valor 60 - contagem 47
Valor 61 - contagem 48
Valor 62 - contagem 56
Valor 63 - 