In [2]:
# quais numeros se repetirão nos ultimoss 5 anos de mega sena 
import numpy as np 
print(np.__version__)

1.26.4


In [12]:
matriz_numeros = np.array([[17, 20, 22, 35, 41, 42],[2, 15, 23, 32, 33, 46],[4, 5, 10, 34, 58, 59],[21, 24, 33, 41, 48, 56],[1, 17, 19, 29, 50, 57]])
print(matriz_numeros)

[[17 20 22 35 41 42]
 [ 2 15 23 32 33 46]
 [ 4  5 10 34 58 59]
 [21 24 33 41 48 56]
 [ 1 17 19 29 50 57]]


In [20]:
# revificando quais números se repetem 
valor_unico , contagem = np.unique(matriz_numeros, return_counts=True)
for valor, cont in zip(valor_unico, contagem):
    print("Valor {} repeti {} ".format(valor, cont))

Valor 1 repeti 1 
Valor 2 repeti 1 
Valor 4 repeti 1 
Valor 5 repeti 1 
Valor 10 repeti 1 
Valor 15 repeti 1 
Valor 17 repeti 2 
Valor 19 repeti 1 
Valor 20 repeti 1 
Valor 21 repeti 1 
Valor 22 repeti 1 
Valor 23 repeti 1 
Valor 24 repeti 1 
Valor 29 repeti 1 
Valor 32 repeti 1 
Valor 33 repeti 2 
Valor 34 repeti 1 
Valor 35 repeti 1 
Valor 41 repeti 2 
Valor 42 repeti 1 
Valor 46 repeti 1 
Valor 48 repeti 1 
Valor 50 repeti 1 
Valor 56 repeti 1 
Valor 57 repeti 1 
Valor 58 repeti 1 
Valor 59 repeti 1 


In [18]:
# qual valor se repeti mais
repeti = valor_repeti = 0 
indice = 1
print('O valor que se repeti mais é: ')
for valor, cont in zip(valor_unico, contagem):
    if cont > indice:
        valor_repeti = valor
        repeti = cont
        print('Valor {} - repeti {} '.format(valor_repeti, repeti))

O valor que se repeti mais é: 
Valor 17 - repeti 2 
Valor 33 - repeti 2 
Valor 41 - repeti 2 


In [19]:
# qual valor se repeti menos
repeti = valor_repeti = 0 
indice = 1
print('O valor que se repeti menos é: ')
for valor, cont in zip(valor_unico, contagem):
    if cont <= indice:
        valor_repeti = valor
        repeti = cont
        print('Valor {} - repeti {} '.format(valor_repeti, repeti))

O valor que se repeti menos é: 
Valor 1 - repeti 1 
Valor 2 - repeti 1 
Valor 4 - repeti 1 
Valor 5 - repeti 1 
Valor 10 - repeti 1 
Valor 15 - repeti 1 
Valor 19 - repeti 1 
Valor 20 - repeti 1 
Valor 21 - repeti 1 
Valor 22 - repeti 1 
Valor 23 - repeti 1 
Valor 24 - repeti 1 
Valor 29 - repeti 1 
Valor 32 - repeti 1 
Valor 34 - repeti 1 
Valor 35 - repeti 1 
Valor 42 - repeti 1 
Valor 46 - repeti 1 
Valor 48 - repeti 1 
Valor 50 - repeti 1 
Valor 56 - repeti 1 
Valor 57 - repeti 1 
Valor 58 - repeti 1 
Valor 59 - repeti 1 


In [29]:
# soma dos numeros de cada ano
anos = len(matriz_numeros)
ano = [0,1,2,3,4]
print('Soma dos valores por ano: ')
soma_ano = 0
for i in range(anos):
    soma_ano = np.sum(matriz_numeros[i])
    print(f'Ano de 202{ano[i]} = ',soma_ano)

Soma dos valores por ano: 
Ano de 2020 =  177
Ano de 2021 =  151
Ano de 2022 =  170
Ano de 2023 =  223
Ano de 2024 =  173


In [31]:
# soma dos numeros por 5 anos
anos = len(matriz_numeros)
ano = [0,1,2,3,4]
print('Soma dos valores por 5 anos: ')
soma_anos = np.sum(matriz_numeros)
print('Soma: ',soma_anos)


Soma dos valores por 5 anos: 
Soma:  894


In [32]:
# Menor número da matriz 
menor_num = np.min(matriz_numeros)
print(menor_num)

1


In [ ]:
# Maior vlor da matrtiz
maior_valor = np.max(matriz